spring:
  application:
    name: server

  datasource:
    url: jdbc:mysql://localhost:3306/innovation?characterEncoding=utf8
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    stat-view-servlet:
      enabled: true
      url-pattern: /druid/*
      allow: "*"
      login-username: admin
      login-password: 123456
      reset-enable: true

  security:
    jwt:
      expire: 604800
#    user:
#      name: admin
#      password: 123456


management:
  endpoints:
    web:
      exposure:
        include: "*"

      base-path: /actuator


logging:
  level:
    web: info
    root: error
    sql: debug
  file:
    path: logs
  pattern:
    file: logs/app-%d{yyyy-MM-dd}-%i.log.gz
  logback:
    rolling policy:
      max-history: 30
      max-file-size: 20MB

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: edu.wsyu.entity.dto


mybatis-mate:
  cert:
    # 请添加微信wx153666购买授权，不白嫖从我做起！ 测试证书会失效，请勿正式环境使用
    grant: thisIsTestLicense
    license: f4jwpVH/dXJO7OWQA0/nLCn4UIkYMPhNreM4AxdRcQtgWX7P1LLhJcuwkv7irO4Ra5577cSTCFIaT4deKzh937GNkkjTIXw+jtCK1cRCPLdfej20xpkXrchAWJmEEHH4uP2wecz2nDZ5+9McgYY0wMKbhEAfY0vpoXmQCUpKCNL/lD5IpayZVm4oCDj5lSPZpSQqv3vAO/rGKsgCu2lXaocrx6axbzZ4ZgRn6Fcv3v5lyblns2CsIxUoNvh9WOwm2MFnEPNSoXrfJ8FvhOet3SGGZ2OY1xzjIpx4XkV0MJdaMLdstPQqk1dMaHXSwW4zqgoNkFH8ZEu0/6xKxKT9bg==